eTickets/Models/Cinema.cs
using System.ComponentModel.DataAnnotations;

namespace eTickets.Models
{
    public class Cinema
    {
        [Key]
        public int Id { get; set; }
        [Display(Name ="Cinema Logo")]
        [Required(ErrorMessage ="Cinema Logo is required")]
        public string Logo { get; set; }
        [Display(Name = "Cinema Name")]
        [Required(ErrorMessage = "Cinema Name is required")]
        public string Name { get; set; }

        public string Description { get; set; }
        //relationships
        public List<Movie>? Movies { get; set; }

    }
}

eTickets/Controllers/CinemasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using eTickets.Data;
using eTickets.Models;
using eTickets.Data.Services;
using System.Numerics;

namespace eTickets.Controllers
{
    public class CinemasController : Controller
    {
        private readonly ICinemasService _service;

        public CinemasController(ICinemasService service)
        {
            _service = service;
        }

        // GET: Cinemas
        public async Task<IActionResult> Index()
        {
            var result = await _service.GetAllAsync();
            return View(result);
              
        }
        // GET: Cinemas/Create
        public async Task<IActionResult> Create(){
            return View();
        
        }

        //POST: Cinemas/Create
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")]Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);

            }
            await _service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }
        // GET: Cinemas/Edit/1

        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);

        }

        //Post Cinemas/Edit/1
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name, Description")]Cinema cinema)
        {
            if(!ModelState.IsValid)
            {
                return View(cinema);
            }
            await _service.UpdateAsync(id,cinema);
            return RedirectToAction(nameof(Index));
        }

        //GET: Cinemas/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            return View(cinemaDetails);

        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        /*

        // GET: Cinemas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cinemas == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                return NotFound();
            }

            return View(cinema);
        }

        // GET: Cinemas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cinemas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cinema);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        // GET: Cinemas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cinemas == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas.FindAsync(id);
            if (cinema == null)
            {
                return NotFound();
            }
            return View(cinema);
        }

        // POST: Cinemas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (id != cinema.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cinema);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CinemaExists(cinema.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        // GET: Cinemas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cinemas == null)
            {
                return NotFound();
            }

            var cinema = await _context.Cinemas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cinema == null)
            {
                return NotFound();
            }

            return View(cinema);
        }

        // POST: Cinemas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cinemas == null)
            {
                return Problem("Entity set 'AppDbContext.Cinemas'  is null.");
            }
            var cinema = await _context.Cinemas.FindAsync(id);
            if (cinema != null)
            {
                _context.Cinemas.Remove(cinema);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CinemaExists(int id)
        {
          return (_context.Cinemas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        */
    }
}

eTickets/Views/Cinemas/Create.cshtml
@model Cinema;

@{
    ViewData["Title"] = "Create";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a New Cinema</h1>
        </p>
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group text-center">
                <img class="border-info rounded-circle" style="max-width:150px" id="ProfilePicturePreview" />
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("ProfilePictureURL").val();
        }
        )
        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

eTickets/Views/Cinemas/Delete.cshtml
@model eTickets.Models.Cinema;

@{
    ViewData["Title"] = "Delete Cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Delete Confirmation for  for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="max-width: 150px" id="ProfilePicturePreview" />
                </div>
                <div class="form-group">
                    <label asp-for="Logo" class="control-label"></label>
                    <input asp-for="Logo" class="form-control" readonly />
                    <span asp-validation-for="Logo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" readonly />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <form asp-action="Delete">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Confirm" class="btn btn-danger float-right" />
                    </form>



                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })
    </script>
}

eTickets/Views/Cinemas/Details.cshtml
@model eTickets.Models.Cinema;


@{
    ViewData["Title"] = "Details of Cinema";
}


<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Details for @Model.Name</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <div class="form-group text-center">
                    <img class="border-info rounded-circle" style="max-width: 150px" id="ProfilePicturePreview" />
                </div>
                <div class="form-group">
                    <label asp-for="Logo" class="control-label"></label>
                    <input asp-for="Logo" class="form-control" readonly />
                    <span asp-validation-for="Logo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" readonly />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" readonly />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">

                    <a class="btn btn-outline-success float-right" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>

                    <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("#ProfilePictureURL").val();
        })
    </script>
}

eTickets/Views/Cinemas/Edit.cshtml
@model Cinema;

@{
    ViewData["Title"] = "Update Cinema";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Update Cinema</h1>
        </p>
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group text-center">
                <img class="border-info rounded-circle" style="max-width:150px" id="ProfilePicturePreview" />
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $("ProfilePictureURL").val();
        })

        $("#ProfilePictureURL").on("change", function () {
            var output = document.getElementById('ProfilePicturePreview');
            output.src = $(this).val();
        })
    </script>
}

eTickets/Views/Cinemas/Index.cshtml
@model IEnumerable<eTickets.Models.Cinema>

@{
    ViewData["Title"] = "List of Cinemas";
}

<div class="row">

    <div class="col-md-8 offset-md-2">


        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Logo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="align-middle">
                            <img class="rounded-circle" src="@item.Logo" alt="@item.Name" style="max-width:150px">
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="align-middle">
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i>Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-info"><i class="bi bi-eye"></i>Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger text-white"><i class="bi bi-trash"></i>Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div style="position:fixed; right:25px; bottom:25px;" class="text-white">
    <a asp-controller="Cinemas" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Add New
    </a>
</div>